#etcd_net - сеть для http обмена
[etcdserver]
etcd1server ansible_host=10.4.4.215 ansible_port=22 ansible_ssh_pass=Qwerty123 etcd_net=10.4.4.215
etcd2server ansible_host=10.4.4.216 ansible_port=22 ansible_ssh_pass=Qwerty123 etcd_net=10.4.4.216
etcd3server ansible_host=10.4.4.217 ansible_port=22 ansible_ssh_pass=Qwerty123 etcd_net=10.4.4.217

[psqlserver]
psql1server ansible_host=10.4.4.215 ansible_port=22 ansible_ssh_pass=Qwerty123 #hostname=pgs1
psql2server ansible_host=10.4.4.216 ansible_port=22 ansible_ssh_pass=Qwerty123 #hostname=node2
psql3server ansible_host=10.4.4.217 ansible_port=22 ansible_ssh_pass=Qwerty123 #hostname=node3

[proxyserver]
proxy1server ansible_host=10.4.4.215 ansible_port=22 ansible_ssh_pass=Qwerty123 
proxy2server ansible_host=10.4.4.216 ansible_port=22 ansible_ssh_pass=Qwerty123
proxy3server ansible_host=10.4.4.217 ansible_port=22 ansible_ssh_pass=Qwerty123

[astraservers:children]
etcdserver
psqlserver
proxyserver

