pass_repl: "replicator"
pass_postgres: "postgres"

 #Keepalived
VIP: "10.4.4.218"
CLUSTER_NET: "10.4.4.0/24"
ETH_VIP: "eth0"

#PostgresPro ver 14\15\16\17\18
P_VER: "18"

#Path postgres
DATA: "/data"
#WAL если пустой то не используется в работе.
#WAL: "/pgwal"
WAL: ""
